### ISSUE TITLE
Can entrypoint.sh run successfully on a machine with no GPU?

### ISSUE THREAD

**Issue by seh** [shelmangroup/coreos-gpu-installer#3]
Near the end of the steps performed by the _entrypoint.sh_ script, [the `verify_nvidia_installation` function](https://github.com/shelmangroup/coreos-gpu-installer/blob/master/entrypoint.sh#L252-L260) invokes _nvidia-smi_ and _nvidia-modprobe_. I don't expect those would run without error on a machine with no GPU, but what about the rest of the script?

I ask because I'll be invoking this script (running it inside of a Docker or rkt container) when building an AMI for use on Amazon EC2 instances. We usually build our AMIs on impoverished, small instance types—those with no GPUs—and I was considering doing the same here. We'd build the image on a machine without a GPU, but then use the image later with machines that do have at least one GPU.

If we made the `verify_nvidia_installation` step optional (whether by command-line flag or environment variable), could the rest succeed? The `verify_nvidia_installation` function doesn't just check to see whether _nvidia-smi_ succeeds; it also [calls on _nvidia-modprobe_](https://github.com/shelmangroup/coreos-gpu-installer/blob/master/entrypoint.sh#L256-L257), which sounds necessary. I can't tell whether _nvidia-modprobe_ is part of confirming success, or if it's [an essential step](https://github.com/NVIDIA/nvidia-modprobe/blob/master/nvidia-modprobe.c#L161-L181) we need to perform before making use of the GPU.

**Comment by seh** [comment]
Experimenting this morning, I've found that disabling the `verify_nvidia_installation` function isn't enough; the NVIDIA installer fails to complete, displaying the following message:
```
WARNING: You do not appear to have an NVIDIA GPU supported by the 390.46
         NVIDIA Linux graphics driver installed in this system.  For
         further details, please see the appendix SUPPORTED NVIDIA GRAPHICS
         CHIPS in the README available on the Linux driver download page at
         www.nvidia.com.
```
The installer pauses for a while, then displays this failure message:
```
ERROR: Unable to load the kernel module 'nvidia.ko'.  This happens most
       frequently when this kernel module was built against the wrong or
       improperly configured kernel sources, with a version of gcc that
       differs from the one used to build the target kernel, or if a driver
       such as rivafb, nvidiafb, or nouveau is present and prevents the
       NVIDIA kernel module from obtaining ownership of the NVIDIA graphics
       device(s), or no NVIDIA GPU installed in this system is supported by
       this NVIDIA Linux graphics driver release.
       
       Please see the log entries 'Kernel module load error' and 'Kernel
       messages' at the end of the file
       '/usr/local/nvidia/nvidia-installer.log' for more information.
```
Indeed, the last possibility—that no NVIDIA GPU is installed on this system—is the one that holds true.

Given that, the answer to my question here is **no**: the _entrypoint.sh_ script cannot run successfully on a machine with no GPU. It may be possible to do some of the downloading and compiling work on such a machine, but we'd still have to complete the installation step on one with a GPU.

I'll now go try to build an AMI using [an appropriate EC2 instance type](https://aws.amazon.com/ec2/instance-types/#p2).

**Comment by lsjostro** [comment]
Thanks for sharing! That's good to know! Using kubernetes you have the option to taint nodes, where the daemonset only schedule on nodes with the appropriate taint.
