### ISSUE TITLE
Default driver download URL template is out of date

### ISSUE THREAD

**Issue by seh** [shelmangroup/coreos-gpu-installer#4]
In file _entrypoint.sh_, there's [the "NVIDIA_DRIVER_DOWNLOAD_URL" variable](https://github.com/shelmangroup/coreos-gpu-installer/blob/master/entrypoint.sh#L26) that interpolates the prescribed version into the URL from which to download the driver runfile. When choosing a recent driver version like **410.48**, the interpolated URL yields a 404 response from _nvidia.com_. Instead, the URL looks more like this:

_https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_410.48_linux_

It's possible to use [the "NVIDIA_DRIVER_DOWNLOAD_URL" variable](https://github.com/shelmangroup/coreos-gpu-installer/blob/master/entrypoint.sh#L27) to override the template entirely, but we may want to use a more recent template.

Mind you, this driver doesn't build correctly for me yet, but I'm still investigating that problem separately.

**Comment by seh** [comment]
It turns out that we need to make the _Tie::File_ module available to Perl, which is available in Ubuntu in the _perl-modules_ package. I'll start on a patch to see if installing that is enough to allow us to succeed with installing the driver.

**Comment by lsjostro** [comment]
good catch! looking forward to a PR :)

**Comment by seh** [comment]
Please see #5 for my proposed fix.

**Comment by seh** [comment]
Note that for version *410.78*, the download URL is as follows, differing from the template I introduced in #5:

_http://us.download.nvidia.com/XFree86/Linux-x86_64/410.78/NVIDIA-Linux-x86_64-410.78.run_

That looks more like the previous URL template, but that's not all that changed. See #6.
