### ISSUE TITLE
Nvidia runtime not available to use the installed drivers for Docker and Kubernetes

### ISSUE THREAD

**Issue by amoghkashyap** [shelmangroup/coreos-gpu-installer#9]
Hi 

It would be helpful if you could support in setting up nvidia-docker v2 and nvidia runtime environment for using the GPU drivers. The driver installation on Tesla V100 volta 32Gigs and GeForce 1080 Ti  8Gigs works perfectly well and the drivers are installed to /opt as /usr is read only file system in CoreOS distribution. 

CoreOS version installed: 2079.3.0 (Stable)
k8s version: v1.14.1 (flannel)
Docker version 18.06.3-ce, build d7080c1

Hardwares:
**1080Ti Desktop**: Linux coreos-01 4.19.34-coreos #1 SMP Mon Apr 22 20:32:34 -00 2019 x86_64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz GenuineIntel GNU/Linux

![image](https://user-images.githubusercontent.com/32319966/57441409-84663700-7267-11e9-8d49-1dd73f43c4f8.png)

**v100 EDGE**: Linux coreos-01 4.19.34-coreos #1 SMP Mon Apr 22 20:32:34 -00 2019 x86_64 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz GenuineIntel GNU/Linux
 
![image](https://user-images.githubusercontent.com/32319966/57441383-74e6ee00-7267-11e9-85df-72aa89a84d84.png)

**Comment by amoghkashyap** [comment]
@lsjostro 
Also , when I try to create pod with following specs, 
![image](https://user-images.githubusercontent.com/32319966/57443562-f93b7000-726b-11e9-9b20-f07c45ccda95.png)

describing the pod gives the following output: (No GPU available)

![image](https://user-images.githubusercontent.com/32319966/57443608-153f1180-726c-11e9-94fe-4c9aa41529ca.png)

**Comment by lsjostro** [comment]
Have you set up the Nvidia device plugin daemonset?
I have no experience with docker-nvidia runtime 2.0 myself. https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/cmd/nvidia_gpu/README.md

**Comment by lsjostro** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml

**Comment by amoghkashyap** [comment]
Yes, The issue seemed to be that the node affinity was set to schedule only on Google's cloud VMs.
Also, the resource limitations set was causing trouble resetting peers. Thank you for your help.
